version: '3'
services:
  mosaic_backend:
    tty: true
    container_name: mosaic_backend
    image: mosaic_backend
    build:
      context: "./docker"
      dockerfile: Dockerfile
    ports:
      - "11323:1323"
    volumes:
      - ${SRC_DIR}:/go
    working_dir: /go
    env_file: .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
